services:
  api:
    build: .
    ports:
      - "8082:8082"
    networks:
      - dotohtwolocalinfra
    environment:
      ELASTICSEARCH_URIS: http://elasticsearch:9200
      TMDB_API_KEY: ${TMDB_API_KEY:-}

networks:
  dotohtwolocalinfra:
    external: true
