spring.application.name=search

spring.elasticsearch.uris=${ELASTICSEARCH_URIS:http://localhost:9200}

tmdb.api-key=${TMDB_API_KEY:}
tmdb.base-url=https://api.themoviedb.org/3

search.reviewable.fallback-threshold=5
